package:
  name: pykep
  version: "1.1.dev"

source:
  git_url: https://github.com/esa/pykep
  git_tag: master

build:
  number: 1

requirements:
  build:
    - python
    - cmake
    - boost

  run:
    - python
    - boost
    - matplotlib

test:
  requires:
    - cmake

about:
  home: http://esa.github.io/pykep/
  license: The GNU General Public License, version 3.0
  summary: Scientific library providing basic tools for research in interplanetary trajectory design
