package:
  name: pykep
  version: "1.2.0"

source:
  git_url: https://github.com/esa/pykep
  git_tag: 1.2.0

build:
  number: 1

requirements:
  build:
    - python
    - cmake
    - boost <=1.55

  run:
    - python
    - boost <=1.55
    - numpy
    - scipy
    - matplotlib

test:
  requires:
    - cmake

about:
  home: http://esa.github.io/pykep/
  license: The GNU General Public License, version 3.0
  summary: Scientific library providing basic tools for research in interplanetary trajectory design
