package:
  name: suitesparse
  version: "4.2.1"

source:
  fn: SuiteSparse-4.2.1.tar.gz
  url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.2.1.tar.gz

  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python
    - mkl
  run:
    - python
    - mkl

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: GPLv2 and LGPLv2.1
  summary: 'A suite of sparse matrix software'

