package:
  name: instant
  version: "1.4.0"

source:
  fn: instant-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/instant/downloads/instant-1.4.0.tar.gz

build:
  number: 8

requirements:
  build:
    - python
    - libxml2
    - zlib
  run:
    - python
    - libxml2
    - zlib
    - cmake
    - swig

test:
  imports:
    - instant

  commands:
    - instant-clean

about:
  home: http://www.fenicsproject.org
  license: BSD License or GNU Library or Lesser General Public License v3 (LGPLv3)
  summary: 'Instant Inlining of C/C++ in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
