package:
  name: ffc
  version: "1.4.0"

source:
  fn: ffc-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-1.4.0.tar.gz
  #md5: 

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy <1.9
  run:
    - python
    - numpy <1.9
    - ufl
    - fiat
    - instant

test:
  # Python imports
  imports:
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - ffc.tensor
    - ufc

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://fenicsproject.org/
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'The FEniCS Form Compiler'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
