package:
  name: petsc4py
  version: "3.5.1"

source:
  fn: petsc4py-3.5.1.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-3.5.1.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - petsc

  run:
    - python
    - petsc

test:
  imports:
    - petsc4py
    - petsc4py.lib

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license: BSD License
  summary: 'PETSc for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
