package:
  name: slepc
  version: "3.5.1"

source:
  fn: slepc-3.5.1.tar.gz
  url: http://www.grycap.upv.es/slepc/download/distrib/slepc-3.5.1.tar.gz#egg=slepc-3.5.1

build:
  number: 1

requirements:
  build:
    - python
    - petsc

  run:
    - python
    - petsc

test:
  imports:
    - slepc

about:
  home: http://www.grycap.upv.es/slepc/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
