package:
  name: fiat
  version: "1.4.0"

source:
  fn: fiat-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-1.4.0.tar.gz

build:
  number: 9

requirements:
  build:
    - python
  run:
    - python
    - numpy <1.9
    - scientificpython

test:
  imports:
    - FIAT

about:
  home: http://fenicsproject.org/
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'FInite element Automatic Tabulator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
