package:
  name: ufl
  version: "1.4.0"

source:
  fn: ufl-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-1.4.0.tar.gz

build:
  number: 9

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - ufl
    - ufl.algorithms
    - ufl.finiteelement

about:
  home: http://www.fenicsproject.org
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'Unified Form Language'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
