package:
  name: ufl
  version: "1.4.0"

source:
  fn: ufl-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-1.4.0.tar.gz
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
  run:
    - python

test:
  # Python imports
  imports:
    - ufl
    - ufl.algorithms
    - ufl.finiteelement

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.fenicsproject.org
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'Unified Form Language'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
