package:
  name: dolfin
  version: "1.4.0"

source:
  fn: dolfin-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.4.0.tar.gz

build:
    number: 4

requirements:
  build:
    - python
    - numpy <1.9
    - ffc
    - ply
    - boost

  run:
    - python
    - numpy <1.9
    - ffc
    - ufl
    - ply
    - boost

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
