package:
  name: dolfin
  version: "1.4.0"

source:
  fn: dolfin-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.4.0.tar.gz
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - cmake
    - python
    - numpy <1.9
    - sphinx
    - ffc
    - ply

  run:
    - python
    - numpy <1.9
    - ffc
    - ufl
    - ply

test:
  # Python imports
  imports:
    - dolfin

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.fenicsproject.org
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
