package:
  name: dolfin
  version: "1.4.0"

source:
  fn: dolfin-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.4.0.tar.gz

  patches:
    - conditional_cholmod.patch
    - fix_find_scotch.patch

build:
  number: 14

requirements:
  build:
    - cmake
    - python
    - sphinx
    - numpy <1.9
    - vtk
    - qt
    - ffc
    - ply
    - boost
    - petsc <=3.4.5
    - petsc4py <=3.4
    - slepc <=3.4.4

  run:
    - python
    - numpy <1.9
    - vtk
    - qt
    - ffc
    - ufl
    - ply
    - boost
    - petsc <=3.4.5
    - petsc4py <=3.4
    - slepc <=3.4.4

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
