package:
  name: dolfin
  version: "1.4.0"

source:
  fn: dolfin-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.4.0.tar.gz

  patches:
    - find_petsc.patch
    - find_slepc.patch

build:
  number: 11

requirements:
  build:
    - cmake
    - python
    - sphinx
    - numpy <1.9
    - ffc
    - ply
    - boost
    - petsc
    - petsc4py
    - slepc

  run:
    - python
    - numpy <1.9
    - ffc
    - ufl
    - ply
    - boost
    - petsc
    - petsc4py
    - slepc

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
