package:
  name: pygmo
  version: "1.1.dev"

source:
  git_url: https://github.com/esa/pagmo
  git_tag: master

build:
  number: 3

requirements:
  build:
    - python
    - cmake
    - boost <=1.55
    - networkx

  run:
    - python
    - boost <=1.55

test:
  requires:
    - cmake

about:
  home: http://esa.github.io/pagmo/
  license: The GNU General Public License, version 3.0
  summary: A C++ / Python platform to perform parallel computations of optimisation tasks (global and local)
